name: Page Analyzer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: hexlet
          POSTGRES_HOST: localhost
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Create Environment
        env:
          DB_CONNECTION: pgsql
          DB_PORT: 5432
          DB_DATABASE: hexlet
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          DB_HOST: localhost
        run: |
          composer install
          cp .env.example .env
          php artisan key:generate
          php artisan migrate --force

      - name: Run Linter
        run: make lint

      - name: Run Test
        run: php artisan test


      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID_MY}}
        with:
          coverageCommand: make test-coverage
          coverageLocations: ${{github.workspace}}/coverage-report:clover
