name: Task Manager

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ 'ubuntu-latest']
        php-versions: [ '7.4' ]
        include:
          - operating-system: 'ubuntu-latest'
            php-versions: '7.4'

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: 1
          POSTGRES_DB: hexlet
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run Linter
        run: make lint

      - name: Notify deploy to Rollbar
        uses: rollbar/github-deploy-action@1.1.0
        id: rollbar_deploy
        with:
          environment: 'production'
          version: ${{ github.sha }}
        env:
          ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}

      - name: Laravel Migrate
        env:
          DB_CONNECTION: pgsql
          DB_PORT: 5432
          DB_DATABASE: hexlet
          DB_USERNAME: postgres
          DB_PASSWORD: 1
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan migrate --force
      - name: Run Test
        run: php artisan test


      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID_MY}}
        with:
          coverageCommand: make test-coverage
          coverageLocations: ${{github.workspace}}/coverage-report:clover
